"""Matis devices properties."""

from enum import auto, Enum


class MatisProperty(Enum):
    """A particular device usually has a subset of these."""

    MODBUS_ADDRESS = auto()
    SERIAL_BAUDRATE = auto()
    SERIAL_PARITY = auto()
    SERIAL_STOP_BITS = auto()
    SYSTEM_STATUS_CONTROL = auto()
    SYSTEM_UPGRADE_CONTROL = auto()
    SYSTEM_CLOCK = auto()
    HARDWARE_ID = auto()
    FIRMWARE_VERSION = auto()
    DISPLAY_STATUS = auto()
    AUX_OUTPUT_STATUS = auto()
    PADLOCK_STATUS = auto()
    HANDLE_LOCATION = auto()
    CONTROL = auto()
    REMOTE_CONTROL_ENABLE = auto()
    CLOSING_DELAY_COMPENSATION = auto()
    OPENING_DELAY_COMPENSATION = auto()
    CLOSING_RESET_COMPENSATION = auto()
    OPENING_RESET_COMPENSATION = auto()
    CLOSING_ACTION_TIME = auto()
    OPENING_ACTION_TIME = auto()
    CLOSING_RESET_TIME = auto()
    OPENING_RESET_TIME = auto()
    OPENING_LOCK_TIME = auto()
    UNLOCK_RESET_TIME = auto()
    MOTOR_RUNNING_TIME = auto()
    COMMAND_CLOSING_TIMES = auto()
    COMMAND_OPENING_TIMES = auto()
    COMMAND_LOCK_TIMES = auto()
    MANUAL_PADLOCK_TIMES = auto()
    MANUAL_CLOSING_TIMES = auto()
    AR_STATUS = auto()
    AR_ENABLE = auto()
    AR_TOTAL_ATTEMPTS = auto()
    AR_CURRENT_ATTEMPT = auto()
    AR_TIMER = auto()
    AR_EXHAUSTED_TIMER = auto()
    AR_WAIT_TIME_1 = auto()
    AR_WAIT_TIME_2 = auto()
    AR_WAIT_TIME_3 = auto()
    AR_WAIT_TIME_4 = auto()
    AR_WAIT_TIME_5 = auto()
    AR_WAIT_TIME_6 = auto()
    AR_WAIT_TIME_7 = auto()
    AR_WAIT_TIME_8 = auto()
    AR_WAIT_TIME_9 = auto()
    AR_WAIT_TIME_10 = auto()
    AR_STABLE_TIME_1 = auto()
    AR_STABLE_TIME_2 = auto()
    AR_STABLE_TIME_3 = auto()
    AR_STABLE_TIME_4 = auto()
    AR_STABLE_TIME_5 = auto()
    AR_STABLE_TIME_6 = auto()
    AR_STABLE_TIME_7 = auto()
    AR_STABLE_TIME_8 = auto()
    AR_STABLE_TIME_9 = auto()
    AR_STABLE_TIME_10 = auto()

    def __str__(self) -> str:
        return self.name.lower()
